name: flutter_app # 应用或包名称
description: A new Flutter application. # 应用或包的描述、简介

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1 # 应用或包的版本号
author: 师春雷 <1558053958@qq.com>
homepage: https://github.com/shichunlei/flutter_app

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies: # 应用或包依赖的其它包或插件
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # AzListView，Flutter 城市列表，联系人列表，自定义Header，索引，悬停效果。
  azlistview: ^0.1.1

  # 扫描二维码
  barcode_scan: ^0.0.8

  # 图表
  charts_flutter: ^0.6.0

  chewie: ^0.9.7

  city_picker: ^0.1.3

  city_pickers: ^0.1.16

  clippy_flutter:
    git:
      url: https://github.com/figengungor/clippy_flutter

  contact_picker: ^0.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # 设备信息
  device_info: ^0.4.0+1

  # 网络请求库
  dio: ^2.1.2

  # 英文单词库
  english_words: ^3.1.5

  fancy_bottom_navigation: ^0.3.2

  # 图标库地址：https://feathericons.com/
  feather_icons_flutter: ^4.7.4

  # 颜色选择器
  flutter_colorpicker: ^0.2.1

  # 刷新加载控件
  flutter_easyrefresh: ^1.2.7

  flutter_gallery_assets: 0.1.6

  flutter_html: ^0.9.6

  flutter_icons: ^0.1.3

  # 侧滑菜单
  flutter_inner_drawer: "^0.2.6"

  # 加载提示组件
  flutter_spinkit: ^2.1.0

  # 瀑布流
  flutter_staggered_grid_view: ^0.2.7

  # banner
  flutter_swiper: ^1.1.6

  flutter_webview_plugin: ^0.3.3

  # 图标库中文地址：http://www.fontawesome.com.cn/
  font_awesome_flutter: ^8.4.0

  giffy_dialog: ^1.3.0

  groovin_material_icons: ^1.1.6

  # 解析html
  html: ^0.13.4+2

  http: ^0.12.0+2

  # 图片选择器
  image_picker: ^0.4.12+1

  # 保存图片
  image_picker_saver: ^0.1.0

  # 引导页
  intro_slider: ^1.2.0

  # 汉字转拼音库 https://github.com/flutterchina/lpinyin
  lpinyin: ^1.0.7

  # The Material Design Icons Icon pack available as set of Flutter Icons.
  material_design_icons_flutter: 3.0.3392

  # 选择多张图片，类似于微信发布朋友圈选择图片
  multi_image_picker: 2.4.11

  outline_material_icons: ^0.1.0

  package_info: ^0.4.0+3

  palette_generator: ^0.1.1

  # PhotoView
  photo_view: ^0.2.4

  # flutter 生成二维码
  qr_flutter: ^2.0.0+51

  #
  rounded_letter: ^0.0.6

  rxdart: ^0.21.0

  share: ^0.6.1

  # SP
  shared_preferences: ^0.5.2

  # 评分控件
  smooth_star_rating: 1.0.1

  # 数据库
  sqflite: ^1.1.5

  # https://github.com/tekartik/synchronized.dart
  synchronized: ^2.1.0

  # 时间线 https://github.com/furkantektas/timeline_list
  timeline_list: ^0.0.4

  # 透明占位图片
  transparent_image: ^0.1.0

  url_launcher: ^5.0.2

  # 视频播放器器
  video_player: ^0.10.0+5

dev_dependencies: # 开发环境依赖的工具包（而不是flutter应用本身依赖的包）
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter. flutter相关的配置选项
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class. https://material.io/tools/icons/?icon=sd_storage&style=baseline
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/weather_backgrounds/
    - assets/data/
    - assets/space_demo.flr
    - packages/flutter_gallery_assets/people/ali_landscape.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
          style: italic
          weight: 700

    - family: CustomIcon
      fonts:
        - asset: assets/fonts/custom/iconfont.ttf
          weight: 400

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
